name: Update Data

on:
  schedule:
    - cron: '0 * * * *' #Every hour 
  workflow_dispatch:  # Manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' 
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute python script 
        run: python get_raw_data.py

      - name: Push new data to github
        run: |
          git config --global user.name 'Ander Fernández'
          git config --global user.email 'anderfernandezj@gmail.com'
          git add -A
          git commit -m "Automatically updated data"
          git push 
